[plugins]
"rocks-config.nvim" = "1.5.0"
"rocks-git.nvim" = "1.4.0"

"rocks-treesitter.nvim" = "scm"
# nvim-treesitter = "0.9.2"

### some deps ###
"plenary.nvim" = "scm"
nvim-web-devicons = "0.99"
alpha-nvim = "scm"
"telescope.nvim" = "scm"
"neo-tree.nvim" = "3.14"
# "chadtree" = { git = "ms-jpq/chadtree", build = "python3 -m chadtree deps" }
# "sfm.nvim" = { git = "dinhhuy258/sfm.nvim" }

####################
#    Appearance    #
####################
"lualine.nvim" = "scm"
"dropbar.nvim" = "8.4.0"

### colorschemes ###
# catpuccin = { version = "1.6.0", opt = true }
"material.nvim" = { version = "scm", opt = true }
# "barbar.nvim" = { git = "romgrk/barbar.nvim" }


####################
#       LSP        #
####################
"mason.nvim" = { version = "1.10.0", opt = true }
"mason-lspconfig.nvim" = { version = "1.27.0", opt = true }
nvim-lspconfig = { version = "0.1.7", opt = true }
"neodev.nvim" = { version = "2.5.2", opt = true }

# treesitter
tree-sitter-lua = "scm"
tree-sitter-toml = "scm"
tree-sitter-vimdoc = "scm"

# cmp
nvim-cmp = "0.0.1"
cmp_luasnip = { version = "scm", opt = true }
cmp-nvim-lsp = { version = "scm", opt = true }
cmp-buffer = { version = "scm", opt = true }
cmp-path = { version = "scm", opt = true }
cmp-cmdline = { version = "scm", opt = true }
tree-sitter-nix = "scm"
tree-sitter-yaml = "scm"
tree-sitter-requirements = "scm"
tree-sitter-markdown = "scm"
tree-sitter-bash = "scm"
tree-sitter-python = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-just = "scm"
tree-sitter-git_config = "scm"

### Utilities ###
"resession.nvim" = { git = "stevearc/resession.nvim" }

### file manager ###
# fm-nvim = { git = "is0n/fm-nvim" }
"tfm.nvim" = { git = "Rolv-Apneseth/tfm.nvim" }

### tabbing ###
"scope.nvim" = { git = "tiagovla/scope.nvim" }
nvim-cokeline = { git = "willothy/nvim-cokeline" }

[config]
plugins_dir = "plugins/"
auto_setup = false

[treesitter]
auto_highlight = "all"
auto_install = true
