-- plugin-coc.nvim
vim.g.coc_global_extensions = {
    'coc-clangd',
    'coc-cmake',
    'coc-css',
    'coc-cssmodules',
    'coc-eslint',
    'coc-git',
    'coc-glslx',
    'coc-go',
    'coc-golines',
    'coc-highlight',
    'coc-html',
    'coc-java',
    'coc-json',
    'coc-ltex',
    'coc-markdownlint',
    'coc-markdown-preview-enhanced',
    'coc-powershell',
    'coc-prettier',
    'coc-pydocstring',
    'coc-pyright',
    'coc-sh',
    'coc-stylelintplus',
    'coc-svg',
    'coc-tailwindcss',
    'coc-tsserver',
    'coc-vimlsp',
    'coc-xml',
    'coc-yaml'
}

